create table if not exists public.ahorros_clientes_credito (
  "fecha_proceso" date,
  "v_ah_cliente" bigint,
  "v_ah_cuenta" bigint,
  "v_ah_nombre" text,
  "fecha_aper" date,
  "fecha_ultmov" date,
  "oficina_cta" bigint,
  "estado_cta" text,
  "prod_bancario" bigint,
  "saldo_disponible" numeric,
  "monto_bloq" numeric,
  "ult_tasa_int" numeric,
  "tiene_bloqueos" numeric,
  "bloqueo_encaje" numeric,
  "v24h" numeric,
  "val_de_creditos" numeric,
  "val_de_debitos" numeric,
  "fecha_ult_capi" date,
  "tipo_cuenta" text,
  "cooplinea" bigint,
  "tarjetas" bigint,
  "credito" bigint,
  "v_fecha_nac" date,
  "edad" bigint,
  "nacionalidad" text,
  "certificadosvalor" numeric,
  "ingresos" numeric,
  "egresos" numeric,
  "menor_edad" bigint,
  "sexo" text,
  "estado_civil" text,
  "fecha_actualizacion" date,
  "v12h" numeric,
  "v48h" numeric,
  "v72h_difer" numeric,
  "int_hoy" numeric,
  "int_acumulado" numeric,
  "saldo_int_decim" numeric
);

create table if not exists public.transacciones_clientes_credito (
  "fecha_trn" date,
  "signo_nc_nd" text,
  "valor_trn" numeric,
  "cuenta" bigint,
  "cliente" bigint,
  "causal_trn" bigint,
  "correccion" text,
  "saldo_contable" numeric,
  "saldo_disponible" numeric
);
